--- 
apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: intellipaat-ingress
spec: 
  rules: 
    - 
      http: 
        paths: 
          - 
            backend: 
              serviceName: apache2
              servicePort: 80
            path: /apache
          - 
            backend: 
              serviceName: custom
              servicePort: 80
            path: /custom

